"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { createContext, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const valueContext = createContext();

export default function RootLayout({ children }) {
  const [query, setQuery] = useState(" ");

  return (
    <valueContext.Provider value={{ query, setQuery }}>
      <html lang="en">
        <body className={inter.className}>
          <div className="pt-[100px]"></div>
          <Header />

          {children}
          <Footer />
        </body>
      </html>
    </valueContext.Provider>
  );
}
